### ISSUE TITLE
autowiring on services

### ISSUE THREAD

**Issue by lukiano** [spring-cloud/spring-cloud-connectors#106]
i have a bean that is created through a serviceinfocreator, based on the data of a serserviceinfo. But the bean, even though is successfully put into the application context, does not seem to be filled its autowired properties, and methods from interfaces like initializingbean or applicationcontextaware aren't called. Is this the expected behaviour?

**Comment by scottfrederick** [comment]
@lukiano Its hard to tell exactly what's going on from your description. Is it possible to share some code in a public sample project or in a gist?

**Comment by spencergibb** [comment]
@scottfrederick sounds like the bean gets created, but none of that beans dependencies get wired in (`@Autowired` and  `ApplicationContextAware` don't work).

**Comment by scottfrederick** [comment]
Yeah, I got that much. I'm wondering *how* the bean gets created and added to the app context. There are several ways to get `ServiceInfo` beans via the API, we'll need to see what parts of the Connectors API is being used to figure out why the beans aren't being wired up properly. 

@lukiano For example, are you using the [spring-cloud-core API](https://github.com/spring-cloud/spring-cloud-connectors/tree/master/spring-cloud-core#connecting-to-a-cloud) directly, or using spring-cloud-spring-service-connector with [XML config](https://github.com/spring-cloud/spring-cloud-connectors/tree/master/spring-cloud-spring-service-connector#the-cloud-namespace) or [Java config](https://github.com/spring-cloud/spring-cloud-connectors/tree/master/spring-cloud-spring-service-connector#the-java-config)? Seeing code samples is probably the fastest way to see what's going on.

**Comment by lukiano** [comment]
Here is a sample: https://github.com/lukiano/spring-cloud-issue
MyConnector is the org.springframework.cloud.CloudConnector
MyService is the ultimate service bean that is injected into the ApplicationContext. It extends InitializingBean, but that is not called.
I would say that right now it assumes that Services injected into the AC have to be fully initialized.

Looking at the source code, MyService is injected via ScannedServiceWrapper which in turn calls GenericCloudServiceConnectorFactory.

**Comment by Skylark95** [comment]
@scottfrederick Any reason why this was closed. This issue appears to still be present. I have a setup very similar to @lukiano sample project, but the bean is a AbstractRoutingDataSource that isn't having the afterPropertiesSet method called on it.

**Comment by scottfrederick** [comment]
@Skylark95 The issue was just closed due to inactivity. There wasn't a resolution but it also wasn't clear if the problem was still affecting anyone. We can re-open if it's causing problems for you.

**Comment by scottfrederick** [comment]
@lukiano @Skylark95 I've spent some time digging into this problem, and have discovered that it is specific to the use of `@ServiceScan` or `@CloudScan` to automatically configure all service connection beans. This mechanism hooks into the Spring application context initialization process to add the appropriate connection beans, but apparently happens too late for all of the bean initialization that you are expecting to happen. 

I've added some tests to confirm this, and I can force a few of the Spring lifecycle interfaces like `InitializingBean` and `BeanFactoryAware` to be invoked, but it will be difficult to force all of them (`ApplicationContextAware`, `BeanClassLoaderAware`, `Disposable`, etc.), and I haven't looked into what it would take to cause autowiring to happen for these beans. 

A workaround for this is to explicitly configure the necessary connection beans instead of using `@ServiceScan` or `@CloudScan`. With the sample provided by @lukiano that would look like this: 

```
@Configuration
public class MyServiceConfiguration extends AbstractCloudConfig {
    @Bean
    public MyService myService() {
        return connectionFactory().service(MyService.class);
    }
}
```

I've confirmed that `InitializingBean.afterPropertiesSet()` gets called on the `MyService` bean, and autowiring works as expected, when using this technique.
