### ISSUE TITLE
Unable to extend cloud connectors to work with Qpid

### ISSUE THREAD

**Issue by johnmcteague** [spring-cloud/spring-cloud-connectors#110]
I am unable to create a custom connector for Qpid due to conflicts with the AMQPServiceInfo class provided for Rabbit.

The URL formats for Qpid and Rabbit differ:

Rabbit:
    amqp://user:pass@host:port/vhost

Qpid:
    amqp://user:pass@clientid/virtualhost?option='value'

The broker host and port is specified in the query params.

The AMQPSerivceInfoCreator will trigger before my custom QpidServiceInfoCreator unless I play games with my classloaders to ensure it is loaded first by ServiceLoader (AMQPServiceInfo will match on URI scheme).

AMQPServiceInfo needs to support both qpid and rabbit or some method of overriding the default uri parsing is required.

**Comment by scottfrederick** [comment]
Apologies for the delay in responding @johnmcteague. 

It looks to me like `AmqpServiceInfo` should handle the Qpid URL syntax and provide the necessary fields. Is there something that you can't get from `AmqpServiceInfo` when that Qpid URL is parsed? 

I would prefer that the ServiceInfo classes didn't do as much parsing and re-building of URLs. If a URL is provided, we should just save that in a field (like `rawUrlSring`) and give it back on request instead of [parsing the URL into discreet fields](https://github.com/scottfrederick/spring-cloud-connectors/blob/master/spring-cloud-core/src/main/java/org/springframework/cloud/util/StandardUriInfoFactory.java#L21-L28) only to put everything [back into a URL again](https://github.com/scottfrederick/spring-cloud-connectors/blob/master/spring-cloud-core/src/main/java/org/springframework/cloud/util/StandardUriInfoFactory.java#L21-L28). If this would solve your problem, I can make that change.

**Comment by scottfrederick** [comment]
@johnmcteague I added a test to verify that parsing of Qpid AMQP URLs into `AmqpServiceInfo` works: https://github.com/spring-cloud/spring-cloud-connectors/commit/494695fd3c9400b5418de83eaab873227487e16b. This should resolve any issues with `AmqpServiceInfoCreator`. Feel free to re-open if you have more issues.
