### ISSUE TITLE
Breaking API change in CloudFoundryServiceInfoCreator in patch release 1.1.1.RELEASE

### ISSUE THREAD

**Issue by davidehringer** [spring-cloud/spring-cloud-connectors#118]
This is more of an FYI than a bug report at this point.  I believe the change in the `CloudFoundryServiceInfoCreator` constructor from `public CloudFoundryServiceInfoCreator(Tags tags, String uriScheme)` to `public CloudFoundryServiceInfoCreator(Tags tags, String... uriSchemes) ` is a source compatible change but not a binary compatible change.  All the connectors we built off of version <= 1.1.0 started breaking at runtime with method not found errors.  Recompiling, without making any changes, against 1.1.1.RELEASE fixes the issue.

**Comment by scottfrederick** [comment]
Yeah, I guess that would be the case. The compiler will think it is OK to pass a single String to a varargs method, but at runtime your code would be looking for a method with an argument of type `String` instead of `String[]`. Hopefully just having to re-compile without any code changes and publish new jars  wasn't too much work for you. 

Thanks for pointing this out for others who may run into it.

**Comment by scottfrederick** [comment]
@davidehringer FYI, I'll be releasing the next version as 1.2.0, since there are a few small issues with backward compatibility from 1.1.0 that affect extension libs (but not client apps).
