### ISSUE TITLE
Multiple ServiceConnectorCreators for one ServiceInfoCreator

### ISSUE THREAD

**Issue by daniel-bub** [spring-cloud/spring-cloud-connectors#121]
Hi,

I have an issue having multiple `ServiceConnectorCreators` for one `ServiceInfoCreator`, where only one of the two `ServiceConnectorCreators` is registered as a bean and accessible using the `@Autowired` annotation. For the second, I need to create a bean manually. The interesting thing is, that the order of the entries in the file `META-INF/services/org.springframework.cloud.service.ServiceConnectorCreator` decides, whether the entry is accessible or not. In my case only the first entry is accessible.

The reason I wan't to create two `ServiceConnectorCreators` for one `ServiceInfoCreator` is that I have a CloudFoundry service that exposes two different interfaces within one service definition. (administration interface and a data access interface)

### CloudFoundry VCAP_SERVICE example

```
{
   "AdminAndDataAccessService": [
      {
          "name": "example",
          "label": "",
          "plan": "Free",
          "credentials": {
             "username": "exampleUser",
             "password": "examplePassowrd",
             "managementUrl": "http://example.com/mgmt",
             "dataAccessUrl": "http://example.com/data"
          }
      },
   ]
}
```

### File org.springframework.cloud.service.ServiceConnectorCreator

> [...]
> com.acme.AdminInterfaceCreator
> com.acme.ClientInterfaceCreator

### File org.springframework.cloud.cloudfoundry.CloudFoundryServiceInfoCreator

> [...]
> com.acme.AdminAndDataAccessServiceInfoCreator

### Resulting behavior

Only the `AdminInterface` is accessible using the `@Autowired` annotation, the `ClientInterface` is not. If the order of the entries is reversed the `ClientInterface` gets accessible and the `AdminInterface` isn't.

**Comment by scottfrederick** [comment]
@daniel-bub Apologies for the delayed response to this question. 

The solution to your problem is to create two different `ServiceInfo` objects (e.g. `ClientServiceInfo` and `AdminServiceInfo`) and populate them from a single `ServiceInfoCreator` class, parsing from a single VCAP_SERVICES entry. You can do this by having your `ServiceInfoCreator` extend `CloudFoundryServiceInfoCreator<BaseCompositeServiceInfo>`, where `BaseCompositeServiceInfo` is a subclass of `ServiceInfo` created for this purpose. 

You can then create a `ServiceConnectorCreator` for each of the `ServiceInfo` classes. 

You can see an example of this being used in the [PHD extension for Connectors](https://github.com/pivotal-cf/spring-cloud-phd-connector/), which has this same requirement.

In particular, see the PhdServiceInfoCreator code here: https://github.com/pivotal-cf/spring-cloud-phd-connector/blob/master/spring-cloud-phd-cloudfoundry-connector/src/main/java/io/pivotal/spring/cloud/cloudfoundry/PhdServiceInfoCreator.java#L26-L36.

**Comment by scottfrederick** [comment]
@daniel-bub I'm going to close this issue pending your testing of the advice above. If that approach doesn't work for you, feel free to re-open the issue.
