### ISSUE TITLE
spring-cloud-heroku-connector can't detect postgresql defined by DATABASE_URL env var

### ISSUE THREAD

**Issue by asinyagin** [spring-cloud/spring-cloud-connectors#148]
Hi,

I'm not sure if it's a bug, probably, i'm missing something.

I'm trying to connect to heroku postgresql with spring-boot-starter-cloud-connectors, but it doesn't detect postgresql: `org.springframework.cloud.CloudException: No unique service matching interface javax.sql.DataSource found. Expected 1, found 0`. Looks like heroku postgres connector expects vars with prefix `HEROKU_POSTGRESQL_` (https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-heroku-connector/src/main/java/org/springframework/cloud/heroku/PostgresqlServiceInfoCreator.java#L23), but heroku stores url of the first (or primary) db in DATABASE_URL. After I've defined `HEROKU_POSTGRESQL_RED_URL` manually, it starts to work.

**Comment by scottfrederick** [comment]
According to the [Heroku docs](https://devcenter.heroku.com/articles/heroku-postgresql#create-a-new-database), the first database created for an application will get a `DATABASE_URL` env var, and subsequent dbs will get a `HEROKU_POSTGRESQL_COLOR_URL` env var. I don't know if this has changed since that Spring Cloud Connectors code was last touched, but that's certainly not what the code is expecting. 

The problem with just looking for `DATABASE_URL` is that the name of the env var alone is ambiguous. We don't know for sure that it is a Postgres db just from that env var name, and the env var name is all we are checking for now. I think we will have to start checking the value of `DATABASE_URL` if that's the only env var available, and detect based on the scheme in the URL like we do in the Cloud Foundry cloud connector.

**Comment by scottfrederick** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-connectors/commit/3b0e497d1d9c54c93021a72cd31f2e95186dcbc0
