### ISSUE TITLE
Change EnvironmentAccessor calls from System.getenv() to ApplicationContext

### ISSUE THREAD

**Issue by sleighsoft** [spring-cloud/spring-cloud-connectors#182]
My suggestion would be to replace the `System.getenv(key)` with the bellow call to `env.getProperty(key)` from the springframework.

```
org.springframework.context.ApplicationContext
org.springframework.context.support.GenericApplicationContext
org.springframework.core.env.Environment
```

This would allow people to write tests that set the environment with the`@TestPropertySource` annotation. Which in turn allows people to fully test classes that extend `AbstractCloudConfig` 

```
ApplicationContext ctx = new GenericApplicationContext();
Environment env = ctx.getEnvironment();
env.getProperty(key)
```

**Comment by scottfrederick** [comment]
@sleighsoft Currently only the `spring-cloud-spring-service-connector` submodule of this project depends on the Spring Framework. The core, Cloud Foundry connector, Heroku Connector, and localconfig connnector subprojects do not have any dependencies on Spring. This was one of the original design goals of the project, with the idea that everything in Connectors except the Spring service connector module could be used in a non-Spring Java project without carrying the weight of Spring. 

We are considering eliminating this design goal in a future major or minor release. This would allow us to use Spring configuration for discovery of components instead of using the Java ServiceLoader mechanism, make it easier to add extension points to the library, and also allow us to do things like you are suggesting here. 

I'm going to mark this as `wontfix` for now, and add this to the list of things to address in a future version, as I don't want to introduce Spring a little at a time without doing the bigger redesign.
