### ISSUE TITLE
maxWaitTime of PoolConfig is not used

### ISSUE THREAD

**Issue by fbeaufume** [spring-cloud/spring-cloud-connectors#308]
To tune the relational database connection pool of a Spring Boot application deployed to Cloud Foundry, we followed https://cloud.spring.io/spring-cloud-connectors/spring-cloud-spring-service-connector.html

More precisely we used something like:

```
@Bean
public DataSource dataSource() {
    PoolConfig poolConfig = new PoolConfig(5, 30, 10000);
    DataSourceConfig dbConfig = new DataSourceConfig(poolConfig, null);
    return connectionFactory().dataSource(dbConfig);
}
```

The first two parameters of the PoolConfig ("minPoolSize" of 5 in the previous example and "maxPoolSize" of 30) are correctly passed to HikariCP but the last parameter ("maxWaitTime" of 10000) is not.

The **"connection timeout"** of the HikariCP pool instance (obtained from HikariDataSource:getConnectionTimeout) **remains to its default value of 30000**.

Note that we used the default connection pool library, i.e. HikariCP.

This issue is confirmed with **Greenwich.SR2**, **Greenwich.SR3** and **Hoxton.RC1**.

Are we missing something?

**Comment by scottfrederick** [comment]
This mapping of `PoolConfig` fields to properties of a `Datasource` implementation bean is done via getter methods on the `PoolConfig` class. You are correct that there are [getters to map the `minPoolSize` and `maxPoolSize` properties](https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-spring-service-connector/src/main/java/org/springframework/cloud/service/PooledServiceConnectorConfig.java#L85-L97) but not `maxWaitTime` to `getConnectionTimeout`. 

Note that the Spring Cloud Connectors project is [now in maintenance mode](https://github.com/spring-cloud/spring-cloud-connectors#spring-cloud-connectors-). This rather clunky and limited mapping of Java bean properties for the various `Datasource` implementations is an example of the friction that this library caused developers and a motivation to replace it with the Spring Boot-centric [Java CFEnv](https://github.com/pivotal-cf/java-cfenv). If you migrate from Connectors to Java CFEnv in a Spring Boot application, you can set Spring Boot properties such as `spring.datasource.hikari.minimum-idle`, `spring.datasource.hikari.maximum-pool-size`, and `spring.datasource.hikari.connection-timeout` instead of the Java config you showed, and you can set [many more properties](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#data-properties) to customize the connection that can't be configured with Connectors. 

If there's a reason why you can't migrate from Connectors to Java CFEnv, I'd consider a Pull Request to support this property mapping for HikariCP in Connectors.

**Comment by fbeaufume** [comment]
Thank you @scottfrederick for the feedback. I'll have a look at Java CFEnv.

**Comment by fbeaufume** [comment]
Hi @scottfrederick 
Java CFEnv seems fine to configure a relational datasource, but does not work as I expected for a MongoDB darabase.
Indeed Java CFEnv replaces the **whole** MongoDB URI. This means that we loose all our custom configuration parameters at the end of the URI such as "?maxWaitTime=5000&connectTimeoutMS=3000".
Should I open a dedicated issue in Java CFEnv ?
The more I use Java CFEnv, the more it feels like an anti-pattern to manage the complexity of VCAP_SERVICES. I wish there were many smaller environment variables such as VCAP_SERVICES_MYDATABASE_HOSTNAME.
Where can I open an issue about such feature request ?

**Comment by scottfrederick** [comment]
> Should I open a dedicated issue in Java CFEnv ?

Yes, please raise this issue in the[ CFEnv project](https://github.com/pivotal-cf/java-cfenv/issues).
