### ISSUE TITLE
HiKari datasource in spring cloud (CF) failed to set PG related connection properties

### ISSUE THREAD

**Issue by iihero** [spring-cloud/spring-cloud-connectors#318]
```               
               PoolConfig poolConfig = new PoolConfig(10, 40, 5000);
		Map<String, Object> connProperties = new HashMap<>();
		connProperties.put("connectionTimeout", 5000);
		connProperties.put("reWriteBatchedInserts", "true");
		ConnectionConfig connConfig = new ConnectionConfig(
				"reWriteBatchedInserts=true&options=-c%20statement_timeout=2000&ApplicationName=ABCD");
		DataSourceConfig dbConfig = new DataSourceConfig(poolConfig, connConfig, null, connProperties);
		DataSource dataSource = connectionFactory().dataSource(dbConfig);
```
I found that no matter we set it in connProperties or in the connConfig String, finally,  the datasource is still used the common properties settings in hikari datasource.  In the above code, only "connectionTimeout" is OK.

Is there any way to make the settings of: "reWriteBatchedInserts" work?

**Comment by scottfrederick** [comment]
Keys passed in a connection properties map or a `ConnectionConfig` must map to fields of the class being created, which in your case appears to be `HikariDataSource`. There is no `reWriteBatchedInserts` method in `HikariDataSource`, so that setting will be ignored. The Postgres JDBC driver [documentation](https://jdbc.postgresql.org/documentation/94/connect.html) says that `reWriteBatchedInserts` should be added to the JDBC URL connection string, and Spring Cloud Connectors does not support modifying the JDBC URL that is read from the service binding information. 

Note that Spring Cloud Connectors is in [maintenance mode](https://github.com/spring-cloud/spring-cloud-connectors#spring-cloud-connectors), and support for this library will end soon. You should replace your usage of Connectors with Java CFEnv or another alternatve.

**Comment by iihero** [comment]
Thanks a lot for your information.  We'll update our code to reflect the change.
