### ISSUE TITLE
Redis connection pool config not working

### ISSUE THREAD

**Issue by sehmusaydogdu** [spring-cloud/spring-cloud-connectors#320]
I created RedisConnectionFactory but the pool is not working as I would like. 
When I looked through "Another Redis Desktop Manager", I saw that there were 19 connections while waiting for a minimum of 30 connections. Could these values be getting crushed in the background?

spring boot parent = 2.0.3
spring-cloud-dependencies= Finchley
spring-cloud-services-dependencies= 2.0.1.RELEASE

```
public class RedisConfig extends AbstractCloudConfig {
 
 @Bean
 public RedisConnectionFactory redisConnectionFactory() {
	PoolConfig pc = new PoolConfig(30, 50, 1000);
	PooledServiceConnectorConfig c = new PooledServiceConnectorConfig(pc);
	return connectionFactory().redisConnectionFactory(c);
 }

 @Bean
 public RedisTemplate<String, Object> redisTemplate() {
	RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>();
	redisTemplate.setConnectionFactory(redisConnectionFactory());
	return redisTemplate;
 }
} 
```

**Comment by scottfrederick** [comment]
@sehmusaydogdu It's hard to tell what might be going wrong from just these code snippets. We'd need a complete minimal sample that reproduces the problem in order to be of any help. 

Please note that [Spring Cloud Connectors is in maintenance mode](https://github.com/spring-cloud/spring-cloud-connectors#spring-cloud-connectors), and will be out of support soon. The versions of Spring Boot and Spring Cloud you are using are out of support. You should consider moving to [Java CFEnv](https://github.com/pivotal-cf/java-cfenv) and supported version of [Spring Boot](https://spring.io/projects/spring-boot#support ) and [Spring Cloud](https://spring.io/projects/spring-cloud#learn).

**Comment by sehmusaydogdu** [comment]
@scottfrederick Thanks for the info. I can't temporarily upgrade as I need some netflix libraries. For now :)
I will try to upgrade to the latest version as soon as possible.

As an alternative solution, I observed that when I edited the repository configuration as follows, it worked as I wanted.

@Bean
public JedisClientConfiguration jedisClientConfiguration() {
	JedisPoolConfig config = new JedisPoolConfig();
	config.setMinIdle(30);
	config.setMaxIdle(100);
	config.setMaxWaitMillis(1000);
	config.setMaxTotal(50);
	return JedisClientConfiguration.builder().usePooling().poolConfig(config).build();
}

@Bean("jedisConnectionFactory")
public JedisConnectionFactory jedisConnectionFactory() {
	final RedisStandaloneConfiguration config = new RedisStandaloneConfiguration();
	config.setHostName("xxxx");
	config.setPassword("xxxx");
	config.setPort(port);
	return new JedisConnectionFactory(config, jedisConnectionFactory());
}

@Bean("redisTemplate")
public RedisTemplate<String, Object> redisTemplate() {
	RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>();
	redisTemplate.setConnectionFactory(jedisConnectionFactory());
	return redisTemplate;
}
