### ISSUE TITLE
Allow user-specified connection pool for DataSource

### ISSUE THREAD

**Issue by ramnivas** [spring-cloud/spring-cloud-connectors#6]
Currently, the `DataSource` creation logic prefers `org.apache.commons.dbcp.BasicDataSource`, then its Tomcat equivalent, and then falls back to Spring's `SimpleDriverDataSource`. We can improve this logic by abstracting pool creation that can also allow utilizing other pools such as [BoneCP](http://jolbox.com)

**Comment by amiri-ge** [comment]
It would be best if this was controlled via environment variables. Otherwise projects will need to create a dependency with spring cloud just to have their data source configured properly.

For example, UAA, does not like the idea of pulling in spring cloud as a dependency (https://github.com/cloudfoundry/uaa/pull/197#issuecomment-128502974). And they make a strong case for not including the dependency. After all UAA does not use spring cloud so why should it pull it in as a dependency?

I feel that if Spring Cloud is going to hijack the construction of established data sources, then it's configuration should come from the environment rather than from the application implementation or configuration. Thoughts?
