### ISSUE TITLE
Provide connector for ElasticSearch

### ISSUE THREAD

**Issue by ramnivas** [spring-cloud/spring-cloud-connectors#78]
Tags are 'pivotal' and 'elasticsearch'

**Comment by bclozel** [comment]
Hey @scottfrederick 

What's the status of this issue? Can I help out with a PR?

Right now I'm working on improving our ElasticSearch integration in [Sagan](https://github.com/spring-io/sagan), in order to use the searchly marketplace service instead of a private ElasticSearch instance.

IMO there are two ways to provide an ElasticSearch connector from the environment.

## HTTP client on a PWS instance

On PWS, the available ElasticSearch service is now provided by Searchly and only allows HTTP communication; use of the native transport client is forbidden. You then have to use an HTTP client such as [Jest](https://github.com/searchbox-io/Jest).

If a Jest library is available on classpath, we can create a `JestClient` using the service information.

```json
{
 "VCAP_SERVICES": {
  "searchly": [
   {
    "credentials": {
     "sslUri": "https://user:password@host.searchly.com",
     "uri": "http://user:password@host.searchly.com"
    },
    "label": "searchly",
    "name": "search-test",
    "plan": "starter",
    "tags": [
     "Developer Tools",
     "search",
     "elasticsearch",
     "Search"
    ]
   }
  ]
 }
}
```

## TransportClient on a CF instance

If an ElasticSearch service with transport client support is available (i.e. the connect URI is using a 9300+ port), we can then create a native client that can be used directly or with spring data elasticsearch.
I don't know if you're aware of such a deployment model on a CF instance.

What do you think?

**Comment by scottfrederick** [comment]
@bclozel A PR for elasticsearch support would be great. 

I like the idea of making the connector smart enough to detect either a Jest or native client on the classpath and creating the appropriate type. The [ServiceConnectionCreator](https://github.com/scottfrederick/spring-cloud-connectors/blob/fab2d644826bf4cc2ff72d4eb9dfb37f22f5ff98/spring-cloud-core/src/main/java/org/springframework/cloud/service/ServiceConnectorCreator.java#L16-16) mechanism is tightly bound to types, so this may not be feasible. If no, preferring the more portable Jest option seems like a safe choice. 

There is an Elasticsearch product for Pivotal Cloud Foundry in pre-release stages currently. I will install that product in a PCF deployment, create and instance, and post an example `VCAP_SERVICES` payload for that product.

**Comment by bclozel** [comment]
Great!
In the meantime I've updated Sagan to use an ElasticSearch marketplace service, using [a custom InfoCreator](https://github.com/spring-io/sagan/blob/7057869a10a09b73f1105c97d0af5e0d790334bd/sagan-common/src/main/java/sagan/support/cloud/ElasticSearchServiceInfoCreator.java).

We can do much better once we've got more information on ElasticSearch support in Pivotal Cloud Foundry.

**Comment by making** [comment]
+1
I'm using searchly on PWS.
Supporting ES would be great.

**Comment by balteo** [comment]
+1

**Comment by scottfrederick** [comment]
Support for elasticsearch should be implemented in an extension project, not in the core.
