### ISSUE TITLE
Provide CloudConnector for GAE

### ISSUE THREAD

**Issue by ramnivas** [spring-cloud/spring-cloud-connectors#81]

**Comment by guyfig** [comment]
Can we change this issue to Support spring-cloud on gCloud (make it more generic for Goole Storage, Compute, Pub/Sub services etc...).
I believe this should be separate like spring-cloud-aws.

**Comment by scottfrederick** [comment]
@guyfig This issue is specifically to support Spring Cloud *Connectors* on GAE. I've changed the title to reflect this. The Spring Cloud Connectors project has a more narrow focus than the Spring Cloud umbrella that it is part of. 

Having a gCloud equivalent to spring-cloud-aws would make sense, but I'm not sure where the best place to provide that feedback would be. @dsyer and @spencergibb can provide guidance there.

**Comment by spencergibb** [comment]
`spring-cloud-aws` was created outside of pivotal and then merged in.  If someone wants to create a `spring-cloud-gcloud` in a similar manner, go for it.

**Comment by guyfig** [comment]
OK. We will do that.

**Comment by scottfrederick** [comment]
Additional CloudConnectors will be implemented in separate projects, not the core project.
