### ISSUE TITLE
AbstractCloudConfig imports classes from Spring data Redis, MongoDB and RabbitMQ

### ISSUE THREAD

**Issue by gauthierj** [spring-cloud/spring-cloud-connectors#88]
Hi,

In project "spring-cloud-spring-service-connector", the object AbstractCloudConfig imports classes from "spring-data-redis", "spring-data-mongodb" and "spring-data-rabbitmq". Therefore it is impossible to extend it to create a DataSource, without adding useless dependencies.

Thanks, regards,

Gauthier

**Comment by codecandy2015** [comment]
Can someone point me how to use spring cloud for a very simple standalone Java Web application !? I would be happy to test it on CF. Thanks

**Comment by scottfrederick** [comment]
@codecandy2015 There are several examples of Java Web applications using Spring Cloud a few comments up in this thread, and the README file in this repo have documentation. Are you looking for something different than what these samples and docs already provide?

**Comment by codecandy2015** [comment]
Hi Scott,
I am trying to write micro services which are based on Jersey. One of the tasks is to read from a MySql table. At the moment I have it running on Tomcat which is working fine using the context.xml. 

I want to use Cloud foundry for this and came here to Spring cloud. It would be a good way to use Spring cloud rather than parsing thru the JSON String for environmental variaables.

I am trying to use it like this in the createEMF method,
```java
public class ServletUtility implements Closeable extends AbstractCloudConfig {
private EntityManagerFactory emf;

public ServletUtility (String pUnit) {
   super();
   this.emf = createEMF(new InitialContext(), pUnit);
}

public EntityManagerFactory createEMF (InitialContext ctx, String persistanceUnit) {
       DataSource ds = connectionFactory().dataSource();
       Map <String, Object> properties = HashMap <String, Objects>();
       properties.put("javax.persistance.nonJtaDataSource", ds);
       properties.put("eclipseLink.target-database", TargetDatabase.MySQL);
       return Persistance.createEntityManagerFactory(persistanceUnit, properties);
     }
}
``` 
Get a null pointer error. You have any suggestions Scott ?!

**Comment by scottfrederick** [comment]
@codecandy2015 Since this question is not related to the original issue, this conversation should be moved to a separate issue. 

The `AbstractCloudConfig` class is designed to be used in a Spring application in a `@Configuration` class. If your app isn't using Spring, or you aren't using Java-based Spring configuration, then `AbstractCloudConfig` isn't going to do what you want it to do. 

Take a look at the [documentation](https://github.com/spring-cloud/spring-cloud-connectors/tree/master/spring-cloud-core#connecting-to-a-cloud) on using Spring Cloud Connectors Core for examples of how to use the Connectors API directly to get a DataSource object.

**Comment by codecandy2015** [comment]
Thanks Scott, I followed the page, got it working ;)! Cheers

**Comment by jhiemer** [comment]
Having exactly the same issue in three projects.

**Comment by scottfrederick** [comment]
Fixed in https://github.com/spring-cloud/spring-cloud-connectors/commit/625040ca1a0699726966997ac0dac40c59fac434. 

The reason that this problem was hard to nail down was that (per my testing anyway) the `NoClassDefFoundException` would only be triggered when the `@Configuration` class that extends `AbstractCloudConfig` was nested within a Spring Boot main class (or possibly nested in any `@Configuration` or `@Component` class). The exception would not get thrown if the `@Configuration` class was a top-level class. There may be other edge cases, but that explains why the problem didn't happen in all the (older, mostly non-Boot) projects listed in the comment above, but happened in many newer (I presume Boot) projects. 

Moving the `ServiceConnectionFactory` class (which is where the `DataSource`, MongoDB, Redis, RabbitMQ dependencies come from) from an inner class of `AbstractCloudConfig` to a top-level class, and making `AbstractCloudConfig` depend on an interface instead of this concrete class, change the way Spring inspects these classes for configuration, and prevents the invocation of the Java refection API that was triggering the `NoClassDefFoundException`.
